# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Tabulation for numeric vectors
#'
#' Base-R's \code{\link[base]{tabulate}} will not tabulate numeric values; this
#' function does.
#'
#' @param y a numeric vector.
#'
#' @return A list with two components: \code{x}, the sorted unique values in
#' \code{y}, and \code{n}, the count associated with each value in \code{x}.
xtabulate <- function(y) {
    .Call(`_metalog_xtabulate`, y)
}

